/* Copyright 2022 REPLACE_WITH_YOUR_NAME
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "quantum.h"

#define XXX KC_NO

#define LAYOUT( \
    K00, K01, K02, K03, K05, K07, K09, K0A, K60, K61, K62, K63, K64, K65, K66, K67, K68, K69, \
    K10, K11, K12, K13, K14, K15, K16, K17, K18, K19, K1A, K70, K71, K72, K73, K74, K75, K76, K77, K78, K79, \
    K20, K21, K22, K23, K24, K25, K26, K27, K28, K29, K2A, K80, K81, K82, K83, K84, K85, K86, K87, K88, K89, \
    K30, K31, K32, K33, K37, K38, K39, K3A, K90, K91, K92, K93, K94, K95, K96, K97, K99, \
    K40, K41, K42, K43, K45, K47, K49, K4A, KA0, KA1, KA2, KA3, KA4, KA5, KA6, KA7, KA8, \
    K50, K51, K52, K53, K54, K55, K56, K57, K58, K59, KB2, KB6, KB7, KB8, KB9  \
) { \
    { K00, K01, K02, K03, XXX, K05, XXX, K07, XXX, K09, K0A }, \
    { K10, K11, K12, K13, K14, K15, K16, K17, K18, K19, K1A }, \
    { K20, K21, K22, K23, K24, K25, K26, K27, K28, K29, K2A }, \
    { K30, K31, K32, K33, XXX, XXX, XXX, K37, K38, K39, K3A }, \
    { K40, K41, K42, K43, XXX, K45, XXX, K47, XXX, K49, K4A }, \
    { K50, K51, K52, K53, K54, K55, K56, K57, K58, K59, XXX }, \
    { K60, K61, K62, K63, K64, K65, K66, K67, K68, K69, XXX }, \
    { K70, K71, K72, K73, K74, K75, K76, K77, K78, K79, XXX }, \
    { K80, K81, K82, K83, K84, K85, K86, K87, K88, K89, XXX }, \
    { K90, K91, K92, K93, K94, K95, K96, K97, XXX, K99, XXX }, \
    { KA0, KA1, KA2, KA3, KA4, KA5, KA6, KA7, KA8, XXX, XXX }, \
    { XXX, XXX, KB2, XXX, XXX, XXX, KB6, KB7, KB8, KB9, XXX }, \
}

// generated by KBFirmware JSON to QMK Parser
// https://noroadsleft.github.io/kbf_qmk_converter/

